### ISSUE TITLE
Please update docker hub pushed copy

### ISSUE THREAD

**Issue by gdevenyi** [aces/CIVET_Full_Project#10]
Existing version is missing https://github.com/aces/CIVET_Full_Project/pull/7 which means QC has no labels.

**Comment by gdevenyi** [comment]
Paging @prioux

**Comment by prioux** [comment]
Seems I missed that earlier this spring

**Comment by prioux** [comment]
I'll have to rediscover how I was building this. The version I use in CBRAIN also contains ANIMAL support with a custom patch to the init.sh file, I'll see if I can propagate these improvements here too

**Comment by gdevenyi** [comment]
If you do a brain/data dump of that stuff I'm happy to integrate things if you don't have time.

**Comment by prioux** [comment]
@gdevenyi Are you able to build the docker container on your side? Because here on the `apt-get install` I get a bunch of error messages all alike:

```
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1~18.04.5_amd64.deb  404  Not Found [IP: 91.189.88.142 80]
```

It may be 1) connectivity issues here at McGill or 2) the ubuntu package servers no longer provide these packages (support ended?)

**Comment by gdevenyi** [comment]
working fine here, looks like you're having some network issues

**Comment by prioux** [comment]
Wait a second... why does this say http instead of https anyway?

**Comment by prioux** [comment]
Seems I had to `docker rmi` a bunch of old overlays, including the cached version of ubuntu 18.04

**Comment by gdevenyi** [comment]
For a long while I couldn't build any fedora rawhide container bits because fedora had completely rebuilt their entire package system with a new build system and hadn't updated their base docker container, so everything would just die.

I have concerns about how stable docker containers are long term... but they're better than the alternative.

**Comment by prioux** [comment]
In CBRAIN we don't use docker containers. We build singularity containers, they end up as just one single large file that is easily moved about, and runs everywhere singularity is installed. Including clusters, where docker doesn't run.

**Comment by prioux** [comment]
I know github is not meant as a chat service, but I just want to say my docker build is still ongoing in the background. I'll push the new container soon. I'll have to think of a proper tag though. It will be `:latest`
 but I'd also like to tag it with a number that represents this particular build.

**Comment by gdevenyi** [comment]
ISO date? 20201014

**Comment by prioux** [comment]
I'm going to go with the first 7 digits of the commit number right here.

```
mcin/civet:latest
mcin/civet:2.1.1
mcin/civet:2.1.1-c3672a8
```

will all refer to the version I'm about to push. And in the future I'll keep older versions that have commit numbers, and I'll adjust :2.1.1 and :latest to point the the most recent one.

**Comment by prioux** [comment]
Darn, I think you're right, a timestamp is better. On dockerhub, it makes things confusing with just the commit ID. I'll adjust that.

**Comment by prioux** [comment]
All done. See:

https://hub.docker.com/repository/docker/mcin/civet/tags?page=1

**Comment by gdevenyi** [comment]
Cheers thank you :+1:

**Comment by prioux** [comment]
I started a new build this morning. Will push at the end of the day when it's ready, and close this issue.

**Comment by gdevenyi** [comment]
Build successful? Can you push please :)

**Comment by prioux** [comment]
Oops. Yes. Build finished last night late. Will push after my current zoom meeting

**Comment by prioux** [comment]
Done. I pushed while in Zoom.
